### ISSUE TITLE
Refactor tests to make use of bionemo home paths in conftest.py

### ISSUE THREAD

**Issue by jstjohn** [NVIDIA/bionemo-framework#30]
When [conftest.py](https://github.com/NVIDIA/bionemo-fw-ea/blob/532a2070d5d81418bb54d14515f6292864cb5ec8/sub-packages/bionemo-contrib/tests/conftest.py) from PR #23 merges, let's update the test paths to checkpoints for geneformer and ESM2 to make use of these paths rather than the relative paths defined in those individual files (see for example PR #28 for the ESM2 test).
```[tasklist]
### Tasks
- [x] ESM2 test paths
- [ ] Geneformer test paths
- [ ] Verify that no other test paths need to be updated
```

**Comment by pstjohn** [comment]
Closed with the new test data management `bionemo.core.data.load` library
