### ISSUE TITLE
Fix NeMo TOT

### ISSUE THREAD

**Issue by jstjohn** [NVIDIA/bionemo-framework#87]
When updating to nemo TOT after @farhadrgh 's bugfix lands: https://github.com/NVIDIA/NeMo/pull/10079, we need to get tests working again: https://nvidia.slack.com/archives/C06ER0PS399/p1723138817281879
```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/bionemo-fw-ea/pull/86
- [x] Remove restriction to limit pytorch-lightning to less than 2.4
- [ ] https://github.com/NVIDIA/bionemo-fw-ea/pull/84
- [x] Fix tests
```
